import type { MovieDetails, MovieSummary } from "./types";

type RawDemoMovie = Omit<MovieDetails, "similar"> & {
  similarIds: number[];
};

const rawDemoMovies: RawDemoMovie[] = [
  {
    tmdb_id: 496243,
    title: "寄生虫",
    original_title: "Parasite",
    poster_path: "/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
    backdrop_path: null,
    release_date: "2019-05-30",
    vote_average: 8.5,
    vote_count: 18350,
    genres: ["剧情", "喜剧", "惊悚"],
    overview:
      "基宇一家四口住在半地下室里，靠折披萨盒维持生计。一次偶然的机会，基宇进入富人家做家教，随后一家人像寄生虫一样逐渐渗透进豪宅，直到一场暴雨揭开了地下的秘密。",
    original_language: "ko",
    popularity: 68.4,
    runtime: 132,
    certification: "R",
    certification_country: "US",
    director: ["奉俊昊"],
    writers: ["奉俊昊", "韩进元"],
    cast: [
      { id: 880, name: "宋康昊", character: "金基泽", profile_path: null, order: 0 },
      { id: 151772, name: "李善均", character: "朴东益", profile_path: null, order: 1 },
      { id: 148882, name: "赵汝贞", character: "朴妍教", profile_path: null, order: 2 },
      { id: 134880, name: "崔宇植", character: "金基宇", profile_path: null, order: 3 },
      { id: 154683, name: "朴素丹", character: "金基婷", profile_path: null, order: 4 },
      { id: 1089318, name: "李姃垠", character: "文光", profile_path: null, order: 5 },
    ],
    keywords: ["class differences", "family", "satire", "social commentary", "survival", "wealth"],
    videos: [],
    imdb_id: "tt6751668",
    production_countries: ["韩国"],
    status: "Released",
    ai_tags: ["Social Satire", "Darkly Comic", "Class Tension", "Twist Narrative", "Domestic Thriller"],
    similarIds: [455, 2730, 44214, 64690],
  },
  {
    tmdb_id: 27205,
    title: "盗梦空间",
    original_title: "Inception",
    poster_path: "/9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg",
    backdrop_path: null,
    release_date: "2010-07-16",
    vote_average: 8.4,
    vote_count: 36950,
    genres: ["动作", "科幻", "冒险"],
    overview:
      "柯布是一名擅长潜入他人潜意识窃取秘密的职业盗梦者。为了回到家人身边，他接下最后一项不可能的任务：在目标潜意识深处植入一个想法。",
    original_language: "en",
    popularity: 88.2,
    runtime: 148,
    certification: "PG-13",
    certification_country: "US",
    director: ["克里斯托弗·诺兰"],
    writers: ["克里斯托弗·诺兰"],
    cast: [
      { id: 525, name: "莱昂纳多·迪卡普里奥", character: "Dom Cobb", profile_path: null, order: 0 },
      { id: 112, name: "约瑟夫·高登-莱维特", character: "Arthur", profile_path: null, order: 1 },
      { id: 1245, name: "艾伦·佩吉", character: "Ariadne", profile_path: null, order: 2 },
      { id: 103, name: "汤姆·哈迪", character: "Eames", profile_path: null, order: 3 },
      { id: 6193, name: "渡边谦", character: "Saito", profile_path: null, order: 4 },
      { id: 4785, name: "玛丽昂·歌迪亚", character: "Mal", profile_path: null, order: 5 },
    ],
    keywords: ["dream", "subconscious", "heist", "maze", "time", "memory"],
    videos: [],
    imdb_id: "tt1375666",
    production_countries: ["美国", "英国"],
    status: "Released",
    ai_tags: ["Mind-Bending", "High Concept", "Heist", "Dream Logic", "Blockbuster"],
    similarIds: [1955, 10494, 454, 152601],
  },
  {
    tmdb_id: 44214,
    title: "黑天鹅",
    original_title: "Black Swan",
    poster_path: null,
    backdrop_path: null,
    release_date: "2010-12-03",
    vote_average: 7.7,
    vote_count: 18120,
    genres: ["剧情", "惊悚"],
    overview:
      "芭蕾舞演员妮娜获得了《天鹅湖》中的双面主角。白天鹅要求纯洁克制，黑天鹅要求放纵狂野。为了完美诠释角色，她开始逐渐失去对现实的掌控。",
    original_language: "en",
    popularity: 54.8,
    runtime: 108,
    certification: "R",
    certification_country: "US",
    director: ["达伦·阿伦诺夫斯基"],
    writers: ["Mark Heyman", "Andres Heinz", "John McLaughlin"],
    cast: [
      { id: 16828, name: "娜塔莉·波特曼", character: "Nina Sayers", profile_path: null, order: 0 },
      { id: 2331, name: "文森特·卡索", character: "Thomas Leroy", profile_path: null, order: 1 },
      { id: 20582, name: "米拉·库尼斯", character: "Lily", profile_path: null, order: 2 },
      { id: 1901, name: "芭芭拉·赫希", character: "Erica Sayers", profile_path: null, order: 3 },
      { id: 614, name: "薇诺娜·瑞德", character: "Beth MacIntyre", profile_path: null, order: 4 },
    ],
    keywords: ["ballet", "obsession", "mental breakdown", "double", "perfectionism", "hallucination"],
    videos: [],
    imdb_id: "tt0947798",
    production_countries: ["美国"],
    status: "Released",
    ai_tags: ["Psychological", "Dark", "Obsessive", "Body Horror", "Artistic Madness"],
    similarIds: [4553, 10494, 641, 454],
  },
  {
    tmdb_id: 670,
    title: "老男孩",
    original_title: "Oldboy",
    poster_path: null,
    backdrop_path: null,
    release_date: "2003-11-21",
    vote_average: 8.2,
    vote_count: 14480,
    genres: ["动作", "悬疑", "惊悚"],
    overview:
      "吴大秀被无故囚禁十五年，某天突然被放出。他必须在五天内找到幕后黑手，而真相将他拖入一个关于复仇与乱伦的深渊。",
    original_language: "ko",
    popularity: 48.7,
    runtime: 120,
    certification: "R",
    certification_country: "US",
    director: ["朴赞郁"],
    writers: ["朴赞郁", "黄祖润", "林俊亨"],
    cast: [
      { id: 1042, name: "崔岷植", character: "Oh Dae-su", profile_path: null, order: 0 },
      { id: 1046, name: "刘智泰", character: "Lee Woo-jin", profile_path: null, order: 1 },
      { id: 1047, name: "姜惠贞", character: "Mi-do", profile_path: null, order: 2 },
    ],
    keywords: ["revenge", "imprisonment", "identity", "amnesia", "twist ending", "violence"],
    videos: [],
    imdb_id: "tt0364569",
    production_countries: ["韩国"],
    status: "Released",
    ai_tags: ["Revenge", "Brutal", "Twisted", "Neo-Noir", "Cinematic Shock"],
    similarIds: [4553, 44214, 455, 475557],
  },
  {
    tmdb_id: 4553,
    title: "机械师",
    original_title: "The Machinist",
    poster_path: null,
    backdrop_path: null,
    release_date: "2004-10-22",
    vote_average: 7.6,
    vote_count: 6250,
    genres: ["剧情", "悬疑", "惊悚"],
    overview:
      "机床工人特雷弗已经一年没有合眼。身体日渐枯槁，工厂里出现没人见过的同事，冰箱上的纸条越来越多。他必须弄清楚自己到底遗忘了什么。",
    original_language: "en",
    popularity: 31.2,
    runtime: 101,
    certification: "R",
    certification_country: "US",
    director: ["布拉德·安德森"],
    writers: ["Scott Kosar"],
    cast: [
      { id: 3894, name: "克里斯蒂安·贝尔", character: "Trevor Reznik", profile_path: null, order: 0 },
      { id: 6130, name: "詹妮弗·杰森·李", character: "Stevie", profile_path: null, order: 1 },
      { id: 37260, name: "艾塔娜·桑切斯-希洪", character: "Marie", profile_path: null, order: 2 },
    ],
    keywords: ["insomnia", "paranoia", "guilt", "psychological", "memory", "identity"],
    videos: [],
    imdb_id: "tt0361862",
    production_countries: ["美国", "西班牙"],
    status: "Released",
    ai_tags: ["Psychological", "Sleepless", "Paranoid", "Slow Burn", "Existential"],
    similarIds: [44214, 10494, 641, 454],
  },
  {
    tmdb_id: 11324,
    title: "禁闭岛",
    original_title: "Shutter Island",
    poster_path: null,
    backdrop_path: null,
    release_date: "2010-02-19",
    vote_average: 8.2,
    vote_count: 22810,
    genres: ["悬疑", "惊悚", "剧情"],
    overview:
      "联邦探员泰迪与搭档前往孤岛精神病院调查失踪案。暴风雨让一切与世隔绝，记忆碎片与现实不断交错，最终真相颠覆了他对自己的认知。",
    original_language: "en",
    popularity: 49.6,
    runtime: 138,
    certification: "R",
    certification_country: "US",
    director: ["马丁·斯科塞斯"],
    writers: ["Laeta Kalogridis"],
    cast: [
      { id: 525, name: "莱昂纳多·迪卡普里奥", character: "Teddy Daniels", profile_path: null, order: 0 },
      { id: 1734, name: "马克·鲁弗洛", character: "Chuck Aule", profile_path: null, order: 1 },
      { id: 1813, name: "本·金斯利", character: "Dr. John Cawley", profile_path: null, order: 2 },
      { id: 1269, name: "米歇尔·威廉姆斯", character: "Dolores Chanal", profile_path: null, order: 3 },
    ],
    keywords: ["island", "asylum", "memory", "trauma", "conspiracy", "unreliable narrator"],
    videos: [],
    imdb_id: "tt1130884",
    production_countries: ["美国"],
    status: "Released",
    ai_tags: ["Psychological", "Gothic", "Mind Games", "Trauma", "Atmospheric"],
    similarIds: [4553, 44214, 454, 10494],
  },
  {
    tmdb_id: 64690,
    title: "亡命驾驶",
    original_title: "Drive",
    poster_path: null,
    backdrop_path: null,
    release_date: "2011-09-16",
    vote_average: 7.6,
    vote_count: 13420,
    genres: ["犯罪", "剧情", "动作"],
    overview:
      "白天是好莱坞特技车手，晚上为劫匪提供逃亡驾驶。沉默寡言的他爱上邻居后卷入一场血腥黑帮交易，被逼露出隐藏已久的暴力。",
    original_language: "en",
    popularity: 41.3,
    runtime: 100,
    certification: "R",
    certification_country: "US",
    director: ["尼古拉斯·温丁·雷弗恩"],
    writers: ["Hossein Amini"],
    cast: [
      { id: 30614, name: "瑞恩·高斯林", character: "Driver", profile_path: null, order: 0 },
      { id: 10297, name: "凯瑞·穆里根", character: "Irene", profile_path: null, order: 1 },
      { id: 4783, name: "布莱恩·科兰斯顿", character: "Shannon", profile_path: null, order: 2 },
      { id: 17419, name: "艾伯特·布鲁克斯", character: "Bernie Rose", profile_path: null, order: 3 },
    ],
    keywords: ["neo noir", "heist", "loneliness", "violence", "stunt driver", "synth"],
    videos: [],
    imdb_id: "tt0780504",
    production_countries: ["美国"],
    status: "Released",
    ai_tags: ["Neo-Noir", "Stylized", "Minimal", "Violent", "Atmospheric"],
    similarIds: [455, 475557, 6977, 670],
  },
  {
    tmdb_id: 455,
    title: "燃烧",
    original_title: "Burning",
    poster_path: null,
    backdrop_path: null,
    release_date: "2018-05-17",
    vote_average: 7.5,
    vote_count: 3180,
    genres: ["剧情", "悬疑", "惊悚"],
    overview:
      "送货员钟秀重逢童年邻居海美，两人开始暧昧。海美从非洲带回神秘富家子本，本向钟秀展示一种奇怪的小爱好。海美失踪后，真相在沉默与火光中慢慢浮现。",
    original_language: "ko",
    popularity: 24.7,
    runtime: 148,
    certification: "NR",
    certification_country: "US",
    director: ["李沧东"],
    writers: ["李沧东", "吴正美"],
    cast: [
      { id: 936590, name: "刘亚仁", character: "Lee Jong-su", profile_path: null, order: 0 },
      { id: 1448904, name: "全钟瑞", character: "Shin Hae-mi", profile_path: null, order: 1 },
      { id: 1448903, name: "史蒂文·元", character: "Ben", profile_path: null, order: 2 },
    ],
    keywords: ["murakami", "class", "loneliness", "slow burn", "mystery", "obsession"],
    videos: [],
    imdb_id: "tt7282468",
    production_countries: ["韩国"],
    status: "Released",
    ai_tags: ["Slow Burn", "Realism", "Melancholic", "Class Tension", "Psychological"],
    similarIds: [496243, 2730, 666277, 454],
  },
  {
    tmdb_id: 454,
    title: "穆赫兰道",
    original_title: "Mulholland Drive",
    poster_path: null,
    backdrop_path: null,
    release_date: "2001-10-19",
    vote_average: 8.0,
    vote_count: 7360,
    genres: ["剧情", "悬疑", "惊悚"],
    overview:
      "车祸后的女人带着失忆走进好莱坞，与追寻演员梦的贝蒂相遇。两人共同寻找一个谜一样的女人，梦境、欲望与好莱坞现实在洛杉矶夜色中互相吞噬。",
    original_language: "en",
    popularity: 37.9,
    runtime: 147,
    certification: "R",
    certification_country: "US",
    director: ["大卫·林奇"],
    writers: ["大卫·林奇"],
    cast: [
      { id: 619, name: "娜奥米·沃茨", character: "Betty Elms / Diane Selwyn", profile_path: null, order: 0 },
      { id: 620, name: "劳拉·哈灵", character: "Rita / Camilla Rhodes", profile_path: null, order: 1 },
      { id: 623, name: "安·米勒", character: "Coco", profile_path: null, order: 2 },
    ],
    keywords: ["dream", "hollywood", "identity", "surreal", "memory", "ambition"],
    videos: [],
    imdb_id: "tt0166924",
    production_countries: ["美国", "法国"],
    status: "Released",
    ai_tags: ["Surreal", "Dreamlike", "Neo-Noir", "Ambiguous", "Experimental"],
    similarIds: [44214, 10494, 4553, 11324],
  },
  {
    tmdb_id: 10494,
    title: "未麻的部屋",
    original_title: "Perfect Blue",
    poster_path: null,
    backdrop_path: null,
    release_date: "1997-08-20",
    vote_average: 8.0,
    vote_count: 3090,
    genres: ["动画", "悬疑", "惊悚"],
    overview:
      "偶像歌手未麻转型演员，却不断收到骚扰信件，身边也接连发生命案。演出与现实的边界逐渐模糊，她开始分不清谁在扮演谁。",
    original_language: "ja",
    popularity: 34.6,
    runtime: 81,
    certification: "R",
    certification_country: "US",
    director: ["今敏"],
    writers: ["村井贞之"],
    cast: [
      { id: 129524, name: "岩男润子", character: "Mima Kirigoe", profile_path: null, order: 0 },
      { id: 129525, name: "松本梨香", character: "Rumi", profile_path: null, order: 1 },
      { id: 129526, name: "辻亲八", character: "Mamoru Uchida", profile_path: null, order: 2 },
    ],
    keywords: ["idol", "identity", "stalking", "mental breakdown", "surveillance", "reality"],
    videos: [],
    imdb_id: "tt0156887",
    production_countries: ["日本"],
    status: "Released",
    ai_tags: ["Psychological", "Surreal", "Meta", "Identity Crisis", "Thriller"],
    similarIds: [44214, 4553, 454, 641],
  },
  {
    tmdb_id: 641,
    title: "梦之安魂曲",
    original_title: "Requiem for a Dream",
    poster_path: null,
    backdrop_path: null,
    release_date: "2000-10-27",
    vote_average: 8.1,
    vote_count: 10480,
    genres: ["剧情"],
    overview:
      "四个渴望美好生活的人被药物和欲望拖入自我毁灭。布鲁克林夏日里闪闪发光的梦，最终在冷漠的冬天变成破碎的幻象。",
    original_language: "en",
    popularity: 44.9,
    runtime: 102,
    certification: "R",
    certification_country: "US",
    director: ["达伦·阿伦诺夫斯基"],
    writers: ["达伦·阿伦诺夫斯基", "Hubert Selby Jr."],
    cast: [
      { id: 660, name: "艾伦·伯斯汀", character: "Sara Goldfarb", profile_path: null, order: 0 },
      { id: 190, name: "杰瑞德·莱托", character: "Harry Goldfarb", profile_path: null, order: 1 },
      { id: 1232, name: "詹妮弗·康纳利", character: "Marion Silver", profile_path: null, order: 2 },
    ],
    keywords: ["addiction", "dream", "self destruction", "drugs", "despair", "mother"],
    videos: [],
    imdb_id: "tt0180093",
    production_countries: ["美国"],
    status: "Released",
    ai_tags: ["Intense", "Despair", "Psychedelic", "Downward Spiral", "Emotional"],
    similarIds: [4553, 44214, 475557, 454],
  },
  {
    tmdb_id: 6977,
    title: "老无所依",
    original_title: "No Country for Old Men",
    poster_path: null,
    backdrop_path: null,
    release_date: "2007-11-09",
    vote_average: 8.1,
    vote_count: 12190,
    genres: ["犯罪", "剧情", "惊悚"],
    overview:
      "猎人摩斯在沙漠中发现毒贩交易的残局和两百万现金。冷血杀手齐格沿路追踪，警长贝尔试图理解这个他越来越无法掌控的世界。",
    original_language: "en",
    popularity: 39.4,
    runtime: 122,
    certification: "R",
    certification_country: "US",
    director: ["乔尔·科恩", "伊桑·科恩"],
    writers: ["乔尔·科恩", "伊桑·科恩"],
    cast: [
      { id: 392, name: "哈维尔·巴登", character: "Anton Chigurh", profile_path: null, order: 0 },
      { id: 3114, name: "乔什·布洛林", character: "Llewelyn Moss", profile_path: null, order: 1 },
      { id: 1167, name: "汤米·李·琼斯", character: "Ed Tom Bell", profile_path: null, order: 2 },
    ],
    keywords: ["western", "fate", "violence", "desert", "moral ambiguity", "chase"],
    videos: [],
    imdb_id: "tt0477348",
    production_countries: ["美国"],
    status: "Released",
    ai_tags: ["Minimal", "Fatalistic", "Neo-Western", "Tense", "Moral"],
    similarIds: [64690, 670, 475557, 455],
  },
  {
    tmdb_id: 152601,
    title: "她",
    original_title: "Her",
    poster_path: null,
    backdrop_path: null,
    release_date: "2013-12-18",
    vote_average: 8.0,
    vote_count: 16320,
    genres: ["剧情", "爱情", "科幻"],
    overview:
      "孤独的信件代写人西奥多与人工智能操作系统萨曼莎相爱。这段没有实体的关系让他在未来城市中重新审视亲密、孤独与人的边界。",
    original_language: "en",
    popularity: 46.1,
    runtime: 126,
    certification: "R",
    certification_country: "US",
    director: ["斯派克·琼斯"],
    writers: ["斯派克·琼斯"],
    cast: [
      { id: 1654, name: "华金·菲尼克斯", character: "Theodore Twombly", profile_path: null, order: 0 },
      { id: 408, name: "斯嘉丽·约翰逊", character: "Samantha", profile_path: null, order: 1 },
      { id: 248, name: "艾米·亚当斯", character: "Amy", profile_path: null, order: 2 },
    ],
    keywords: ["artificial intelligence", "loneliness", "love", "near future", "connection", "voice"],
    videos: [],
    imdb_id: "tt1798709",
    production_countries: ["美国"],
    status: "Released",
    ai_tags: ["Tender", "Melancholic", "Near Future", "Romantic", "Quiet"],
    similarIds: [666277, 455, 27205, 329865],
  },
  {
    tmdb_id: 329865,
    title: "降临",
    original_title: "Arrival",
    poster_path: null,
    backdrop_path: null,
    release_date: "2016-11-11",
    vote_average: 7.6,
    vote_count: 15930,
    genres: ["科幻", "剧情", "悬疑"],
    overview:
      "外星飞船悬停在地球各地。语言学家露易丝试图破解七肢桶的语言，却在这个过程中看见了过去、现在与未来的交汇。",
    original_language: "en",
    popularity: 43.8,
    runtime: 116,
    certification: "PG-13",
    certification_country: "US",
    director: ["丹尼斯·维伦纽瓦"],
    writers: ["埃里克·海瑟尔"],
    cast: [
      { id: 3896, name: "艾米·亚当斯", character: "Louise Banks", profile_path: null, order: 0 },
      { id: 3223, name: "杰瑞米·雷纳", character: "Ian Donnelly", profile_path: null, order: 1 },
      { id: 53823, name: "福里斯特·惠特克", character: "Colonel Weber", profile_path: null, order: 2 },
    ],
    keywords: ["language", "time", "alien", "communication", "grief", "memory"],
    videos: [],
    imdb_id: "tt2543164",
    production_countries: ["美国", "加拿大"],
    status: "Released",
    ai_tags: ["Contemplative", "Sci-Fi", "Linguistic", "Emotional", "Slow Reveal"],
    similarIds: [152601, 27205, 666277, 454],
  },
  {
    tmdb_id: 577922,
    title: "仲夏夜惊魂",
    original_title: "Midsommar",
    poster_path: null,
    backdrop_path: null,
    release_date: "2019-07-03",
    vote_average: 7.1,
    vote_count: 6410,
    genres: ["恐怖", "剧情", "悬疑"],
    overview:
      "一群朋友受邀前往瑞典偏远村庄参加仲夏节。白日不落的庆典逐渐露出邪教的底色，失去至亲的丹妮被卷进一场以集体之名展开的仪式。",
    original_language: "en",
    popularity: 29.4,
    runtime: 147,
    certification: "R",
    certification_country: "US",
    director: ["阿里·艾斯特"],
    writers: ["阿里·艾斯特"],
    cast: [
      { id: 206412, name: "弗洛伦丝·皮尤", character: "Dani Ardor", profile_path: null, order: 0 },
      { id: 1074692, name: "杰克·莱诺", character: "Christian Hughes", profile_path: null, order: 1 },
      { id: 22375, name: "威廉·杰克逊·哈珀", character: "Josh", profile_path: null, order: 2 },
    ],
    keywords: ["folk horror", "cult", "grief", "sunlight", "ritual", "community"],
    videos: [],
    imdb_id: "tt8772262",
    production_countries: ["美国", "瑞典"],
    status: "Released",
    ai_tags: ["Folk Horror", "Bright Dread", "Cult", "Grief", "Unsettling"],
    similarIds: [503919, 44214, 10494, 475557],
  },
  {
    tmdb_id: 503919,
    title: "灯塔",
    original_title: "The Lighthouse",
    poster_path: null,
    backdrop_path: null,
    release_date: "2019-10-18",
    vote_average: 7.5,
    vote_count: 4820,
    genres: ["恐怖", "悬疑", "剧情"],
    overview:
      "两名灯塔看守被困在风暴中的孤岛上。酒精、海鸟与黑暗传说让两人的意志互相撕咬，幻觉与真相一起在狂风里崩塌。",
    original_language: "en",
    popularity: 28.8,
    runtime: 109,
    certification: "R",
    certification_country: "US",
    director: ["罗伯特·艾格斯"],
    writers: ["罗伯特·艾格斯", "Max Eggers"],
    cast: [
      { id: 16851, name: "威廉·达福", character: "Thomas Wake", profile_path: null, order: 0 },
      { id: 73457, name: "罗伯特·帕丁森", character: "Ephraim Winslow", profile_path: null, order: 1 },
    ],
    keywords: ["isolation", "madness", "sea", "myth", "black and white", "psychological"],
    videos: [],
    imdb_id: "tt7984734",
    production_countries: ["美国"],
    status: "Released",
    ai_tags: ["Isolation", "Gothic", "Madness", "Monochrome", "Atmospheric"],
    similarIds: [577922, 11324, 4553, 454],
  },
  {
    tmdb_id: 475557,
    title: "好时光",
    original_title: "Good Time",
    poster_path: null,
    backdrop_path: null,
    release_date: "2017-08-11",
    vote_average: 7.3,
    vote_count: 3480,
    genres: ["犯罪", "剧情", "惊悚"],
    overview:
      "哥哥抢劫银行失败后被捕，康尼在纽约的夜色里横冲直撞，想尽一切办法在黎明前把弟弟救出来。每一次选择都让局面更加失控。",
    original_language: "en",
    popularity: 26.6,
    runtime: 101,
    certification: "R",
    certification_country: "US",
    director: ["本·萨弗迪", "约书亚·萨弗迪"],
    writers: ["约书亚·萨弗迪", "罗纳德·布朗斯坦"],
    cast: [
      { id: 108916, name: "罗伯特·帕丁森", character: "Connie Nikas", profile_path: null, order: 0 },
      { id: 1591333, name: "本尼·萨弗迪", character: "Nick Nikas", profile_path: null, order: 1 },
      { id: 15250, name: "詹妮弗·杰森·李", character: "Corey", profile_path: null, order: 2 },
    ],
    keywords: ["heist", "brotherhood", "new york", "desperation", "night", "crime"],
    videos: [],
    imdb_id: "tt5207028",
    production_countries: ["美国"],
    status: "Released",
    ai_tags: ["Gritty", "Tense", "Neon Night", "Desperate", "Urban"],
    similarIds: [64690, 670, 641, 6977],
  },
  {
    tmdb_id: 666277,
    title: "过往人生",
    original_title: "Past Lives",
    poster_path: null,
    backdrop_path: null,
    release_date: "2023-06-02",
    vote_average: 7.8,
    vote_count: 2150,
    genres: ["剧情", "爱情"],
    overview:
      "娜英和家人移民加拿大后，与儿时的青梅竹马海盛断了联系。二十年后两人在纽约重逢，一场关于命运、选择和未走之路的温柔对话就此展开。",
    original_language: "ko",
    popularity: 22.9,
    runtime: 106,
    certification: "PG-13",
    certification_country: "US",
    director: ["席琳·宋"],
    writers: ["席琳·宋"],
    cast: [
      { id: 1687105, name: "格蕾塔·李", character: "Nora Moon", profile_path: null, order: 0 },
      { id: 1821795, name: "刘台午", character: "Hae Sung", profile_path: null, order: 1 },
      { id: 2215628, name: "约翰·马加罗", character: "Arthur", profile_path: null, order: 2 },
    ],
    keywords: ["immigration", "reunion", "fate", "memory", "longing", "quiet"],
    videos: [],
    imdb_id: "tt13238346",
    production_countries: ["美国", "韩国"],
    status: "Released",
    ai_tags: ["Tender", "Melancholic", "Quiet", "Realist", "Longing"],
    similarIds: [455, 152601, 329865, 496243],
  },
  {
    tmdb_id: 290098,
    title: "小姐",
    original_title: "The Handmaiden",
    poster_path: null,
    backdrop_path: null,
    release_date: "2016-06-01",
    vote_average: 8.2,
    vote_count: 3120,
    genres: ["剧情", "悬疑", "爱情"],
    overview:
      "骗子藤原想借女仆淑熙接近贵族小姐秀子，夺取她的遗产。但随着计划推进，两个女人在层层骗局中发现了彼此真实的心。",
    original_language: "ko",
    popularity: 25.1,
    runtime: 145,
    certification: "R",
    certification_country: "US",
    director: ["朴赞郁"],
    writers: ["郑瑞景", "朴赞郁"],
    cast: [
      { id: 1245848, name: "金敏喜", character: "Hideko", profile_path: null, order: 0 },
      { id: 1399481, name: "金泰梨", character: "Sook-hee", profile_path: null, order: 1 },
      { id: 132187, name: "河正宇", character: "Count Fujiwara", profile_path: null, order: 2 },
    ],
    keywords: ["con", "romance", "twist", "colonial era", "power", "desire"],
    videos: [],
    imdb_id: "tt4016934",
    production_countries: ["韩国"],
    status: "Released",
    ai_tags: ["Erotic Thriller", "Twisted", "Period", "Power", "Romantic"],
    similarIds: [670, 455, 44214, 496243],
  },
  {
    tmdb_id: 2730,
    title: "杀人回忆",
    original_title: "Memories of Murder",
    poster_path: null,
    backdrop_path: null,
    release_date: "2003-05-02",
    vote_average: 8.1,
    vote_count: 4230,
    genres: ["犯罪", "剧情", "悬疑"],
    overview:
      "上世纪八十年代的韩国乡村接连发生凶案。本地刑警与首尔来的侦探用完全不同的方式追查，真相却在时代与体制的裂缝中始终无法落地。",
    original_language: "ko",
    popularity: 23.4,
    runtime: 131,
    certification: "NR",
    certification_country: "US",
    director: ["奉俊昊"],
    writers: ["奉俊昊", "沈成宝"],
    cast: [
      { id: 880, name: "宋康昊", character: "Detective Park Doo-man", profile_path: null, order: 0 },
      { id: 1373, name: "金相庆", character: "Detective Seo Tae-yoon", profile_path: null, order: 1 },
      { id: 1374, name: "金罗河", character: "Detective Cho Yong-koo", profile_path: null, order: 2 },
    ],
    keywords: ["serial killer", "true crime", "rural korea", "frustration", "investigation", "memory"],
    videos: [],
    imdb_id: "tt0353969",
    production_countries: ["韩国"],
    status: "Released",
    ai_tags: ["Procedural", "Grim", "Historical", "Frustrating", "True Crime"],
    similarIds: [455, 496243, 6977, 11324],
  },
];

const demoById = new Map(rawDemoMovies.map((movie) => [movie.tmdb_id, movie]));

function toSummary(movie: RawDemoMovie): MovieSummary {
  return {
    tmdb_id: movie.tmdb_id,
    title: movie.title,
    original_title: movie.original_title,
    poster_path: movie.poster_path,
    backdrop_path: movie.backdrop_path,
    release_date: movie.release_date,
    vote_average: movie.vote_average,
    vote_count: movie.vote_count,
    genres: movie.genres,
    overview: movie.overview,
    original_language: movie.original_language,
    popularity: movie.popularity,
  };
}

export const DEMO_MOVIES: MovieDetails[] = rawDemoMovies.map((movie) => ({
  ...movie,
  similar: movie.similarIds
    .map((id) => demoById.get(id))
    .filter((item): item is RawDemoMovie => Boolean(item))
    .map(toSummary),
}));

export function getDemoMovie(tmdbId: number) {
  return DEMO_MOVIES.find((movie) => movie.tmdb_id === Number(tmdbId)) ?? null;
}

export function searchDemoMovies(query: string) {
  const normalized = query.trim().toLowerCase();
  if (!normalized) return DEMO_MOVIES;
  const keywords = normalized.split(/\s+/).filter(Boolean);
  return DEMO_MOVIES.filter((movie) => {
    const haystack = [
      movie.title,
      movie.original_title,
      movie.overview,
      ...movie.genres,
      ...movie.keywords,
      ...movie.ai_tags,
    ]
      .join(" ")
      .toLowerCase();
    return keywords.every((keyword) => haystack.includes(keyword));
  });
}
